[platformio]
default_envs = full_local

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    bblanchon/ArduinoJson
    arduino-libraries/Ethernet
    knolleary/PubSubClient
    mobizt/ESP_SSLClient

[env:stage_sht31_rtc_sd]
build_src_filter =
    -<*>
    +<common/sht31.cpp>
    +<common/ds3231.cpp>
    +<common/sd_logger.cpp>
    +<stages/stage_sht31_rtc_sd.cpp>

[env:stage_ads1115]
build_src_filter =
    -<*>
    +<common/ads1115.cpp>
    +<stages/stage_ads1115.cpp>

[env:stage_ina219_oled]
build_src_filter =
    -<*>
    +<common/ina219.cpp>
    +<common/oled_display.cpp>
    +<stages/stage_ina219_oled.cpp>

[env:stage_sdi12_nano]
build_src_filter =
    -<*>
    +<common/nano_sdi12_receiver.cpp>
    +<stages/stage_sdi12_nano.cpp>

[env:stage_mqtt]
build_src_filter =
    -<*>
    +<common/mqtt_client.cpp>
    +<stages/stage_mqtt.cpp>

[env:full_local]
build_src_filter =
    -<*>
    +<common/*.cpp>
    +<stages/full_local_main.cpp>

[env:full_mqtt]
build_src_filter =
    -<*>
    +<common/*.cpp>
    +<stages/full_mqtt_main.cpp>